-- PetCare database schema
-- Import in phpMyAdmin or: mysql -u root -p < schema.sql

CREATE DATABASE IF NOT EXISTS petcare CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE petcare;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  species VARCHAR(50) NOT NULL,
  breed VARCHAR(100) DEFAULT NULL,
  age DECIMAL(4,1) DEFAULT NULL,
  vaccinations TEXT,
  allergies TEXT,
  photo VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reminders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  task VARCHAR(255) NOT NULL,
  type ENUM('general','medication','vet_appointment') DEFAULT 'general',
  due_date DATE NOT NULL,
  due_time TIME NOT NULL,
  recurrence ENUM('none','daily','weekly','monthly') DEFAULT 'none',
  status ENUM('pending','completed') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS diet_charts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  meal_type VARCHAR(100) NOT NULL,
  quantity VARCHAR(50) NOT NULL,
  frequency VARCHAR(100) DEFAULT NULL,
  notes TEXT,
  date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS health_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  type VARCHAR(50) NOT NULL,
  details TEXT,
  date DATE NOT NULL,
  file_path VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pet_journal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_id INT NOT NULL,
  entry TEXT NOT NULL,
  mood VARCHAR(50) DEFAULT NULL,
  meal VARCHAR(100) DEFAULT NULL,
  poop_log VARCHAR(100) DEFAULT NULL,
  entry_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pet_photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS newsletter (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
